"""Tests for _errortools/metadata.py."""

import namebyauthor as na

from _errortools.metadata import (
    __author__,
    __author_email__,
    __copyright__,
    __description__,
    __license__,
    __title__,
    __url__,
    __fullname__,
    __signature__,
    __slug__,
)

# =============================================================================
# metadatas not using `namebyauthor` module
# =============================================================================


class TestStaticMetadata:
    """Tests for the plain string metadata constants."""

    def test_author_is_string(self):
        assert isinstance(__author__, str)
        assert __author__ == "Evan Yang"

    def test_author_email_is_string(self):
        assert isinstance(__author_email__, str)
        assert __author_email__ == "quantbit@126.com"

    def test_copyright_is_string(self):
        assert isinstance(__copyright__, str)
        assert "Copyright" in __copyright__
        assert __author__ in __copyright__

    def test_description_is_string(self):
        assert isinstance(__description__, str)
        assert __description__ == (
            "errortools - a toolset for working with Python exceptions and warnings and logging."
        )

    def test_license_is_string(self):
        assert isinstance(__license__, str)
        assert __license__ == "MIT"

    def test_title_is_string(self):
        assert isinstance(__title__, str)
        assert __title__ == "errortools"

    def test_url_is_string(self):
        assert isinstance(__url__, str)
        assert "/" in __url__
        assert "github.com" in __url__
        assert "errortools" in __url__
        # Maybe will changes
        # assert __url__ == "https://github.com/more-abc/errortools"

    def test_author_email_looks_like_email(self):
        # Sanity check: email must contain exactly one "@" with text on both sides.
        assert "@" in __author_email__
        local, _, domain = __author_email__.partition("@")
        assert local and domain and "." in domain

    def test_url_uses_https(self):
        assert __url__.startswith("https://")


# =============================================================================
# metadatas generated by `namebyauthor` module
# =============================================================================


class TestNameByAuthorMetadata:
    """Tests for the metadata values produced via the `namebyauthor` helper."""

    def test_fullname_is_string(self):
        assert isinstance(__fullname__, str)
        assert __fullname__ == na.generate_name(__title__, __author__)

    def test_fullname_format(self):
        assert __fullname__ == f"{__title__} by {__author__}"

    def test_slug_is_string(self):
        assert isinstance(__slug__, str)
        assert __slug__ == na.generate_slug(__title__, __author__)

    def test_slug_format(self):
        # namebyauthor.generate_slug returns "<title>-by-<author>".
        assert __slug__ == f"{__title__}-by-{__author__.lower().replace(' ', '-')}"

    def test_signature_is_string(self):
        assert isinstance(__signature__, str)
        assert __signature__ == na.generate_signature(__title__, __author__)

    def test_signature_is_hex(self):
        # The signature is a deterministic hash; it should be lowercase hex.
        hex_chars = set("0123456789abcdef")
        for c in __signature__:
            assert c in hex_chars
