name: Auto Delete Branch
on:
  pull_request:
    types: [closed]
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if (context.payload.pull_request.merged) {
              github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "heads/" + context.payload.pull_request.head.ref
              })
            }