name: Auto Comment Bot

permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  pull_request_target:
    types: [closed]

permissions:
  issues: write
  pull-requests: write
  
jobs:
  welcome-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' || github.event_name == 'pull_request' }}
    steps:
      - name: Auto Welcome Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            Thanks for opening this issue/PR! 😊

            We really appreciate your contribution — your effort helps make the project better. ✨

            Feel free to add any additional details, screenshots, or context here to help us review your work smoothly.

  merged-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merged == true }}
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🎉 PR merged successfully! Thank you for your contribution.