name: CLA Assistant Bot

on:
  issue_comment:
    types:
      - created
      - edited
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  CLA-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        uses: contributor-assistant/github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_APP_PRIVATE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_BOT_TOKEN }}
        with:
          config-path: .github/cla.yml
          path-to-signatures: signatures/cla.json
          branch: master
          allowlist: AbaAbaAba-bot-like[bot]
          lock-pullrequest-unfetched-cla: true
          lock-pr-body: |
            Please sign the CLA by commenting:
            "I have read and agree to the CLA"