name: Trigger Read the Docs build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Read the Docs build
        uses: ammaraskar/read-the-docs-build-action@master
        with:

          project_slug: errortools
          api_token: ${{ secrets.RTD_API_TOKEN }}