name: Trigger Read the Docs Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Read the Docs API
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.RTD_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"branches": ["master"]}' \
            https://readthedocs.org/api/v3/projects/errortools/builds/